import "./globals.css";
import type { Metadata } from "next";
import ConvexClientProvider from "./ConvexClientProvider";

// Define a custom type for the font variable
interface Font {
  variable: string;
  // Add other properties as needed
}

// Create the font variable
const font: Font = {
  variable: "--font-chakra",
  // Add other properties as needed
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.variable}>
        <ConvexClientProvider>{children}</ConvexClientProvider>
      </body>
    </html>
  );
}
